; Listing generated by Microsoft (R) Optimizing Compiler Version 19.10.25017.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Roma\AppData\Local\Temp\.NETFramework,Version=v4.5.2.AssemblyAttributes.cpp"
